Add hook for force reloading
bdarcus/bibtex-actions pull request #124
Opened 2021-05-02 18:11 UTC by publicimageltd

This adds a hook which is run when reloading is forced by pressing C-u.

Note that this hook is not run in a usual refresh, since recreating a bibliography file can take a while and thus should be explicitly requested. Here's my setup, using the function `pullbib-pull` to create the bibliography file on demand:

```emacs-lisp
  (setq bibtex-actions-force-refresh-hook  (list #'pullbib-pull))
```

2021-05-02 19:25 UTC, bdarcus commented
Looks good!

The CI has a few minor warnings you should resolve. You can see them by clicking the "files" tab on the PR.

2021-05-02 20:38 UTC, bdarcus requested changes

2021-05-02 20:38 UTC, bdarcus commented on bibtex-actions.el
> +operations such as a complete export of a Zotero library to a
Aside from addressing the warnings, while I use Zotero myself, could we have a more generic example?

Not a big deal if not ....

2021-05-03 11:21 UTC, bdarcus commented
A question just occurred to me:

This assumes the user explicitly calls this using the prefix argument.

But what if I want to automate this using notify and a script, with Emacs daemon?

2021-05-03 11:57 UTC, bdarcus approved these changes

2021-05-03 12:08 UTC, publicimageltd commented
> Or is this a non-issue; the hook is for user input situations, and this is still available?

Exactly, because you still can pass an explicit argument to `refresh` in order to run the hook without user interaction.

Thanks for merging!

2021-05-03 12:09 UTC, publicimageltd commented
Sorry, wrong button -- just wanted to comment :-)

2021-05-03 12:14 UTC, merged

2021-05-03 12:20 UTC, bdarcus commented
Done.

Probably should add something to the README?

2021-05-03 13:07 UTC, publicimageltd commented
> Probably should add something to the README?

I could do it, but I would prefer you  todo that, since I always have to edit my docs thrice until I am satisfied with them (language problem). I promise I'll include the README for my next PR. Hell, I did not think that it takes /so/ many steps to finish a PR. :-)

2021-05-03 13:18 UTC, bdarcus commented
No problem.

BTW, the docstring warnings from the CI; `checkdoc` will flag those locally.

2021-05-03 15:02 UTC, bdarcus commented
Is pullbib ready enough from your perspective to put as an example in the README, or on the wiki?

I'll test it later, as I do use Zotero and BBT.

2021-05-03 17:33 UTC, publicimageltd commented
Do test pullbib, please! It works for me. Only thing missing is the ability to add extra parameters to the query, e.g. "don't export notes". I think it's not necessary, so I am glad if someone else tests it.

2021-05-03 17:55 UTC, bdarcus commented
I saw you work with `org-roam`; do you make any effort to sync zotero notes with `org-roam`, or do you do all bib note-taking in the later?

The forthcoming PDF viewer and annotation support in Zotero is its first killer feature in a long time.

2021-05-03 18:33 UTC, publicimageltd commented
> I saw you work with org-roam; do you make any effort to sync 
> zotero notes with org-roam, or do you do all bib note-taking in 
> the later?

I only use org-roam; Zotero always felt too clumsy (yikes! mouse 
movements!).
 
> The forthcoming PDF viewer and annotation support in Zotero is 
> its first killer feature in a long time.

I did not know about that and just looked at it! Wow, that's 
really a change, finally! I guess I will not switch to Zotero, 
however, as long as it insists on using a mouse. Also, I love 
Emacs' flexibility: I can copy and paste, move to registers, 
quickly write a defun to collect stuff in a separate buffer, then 
save it, and and and...

I will rewrite my delve package for the new org roam version v2; 
but I am still looking for a new concept for the UI. I get more 
and more convinced that the completing-read-style of doing things 
is the Emacs way, so my current implementation, which is basically 
a list application, seems too static. If I have some time, I'll 
look at embark -- maybe making  snapshots of collection of 
org-roam pages, with some sensible actions to work with them, can 
be the killer feature I am looking for.

2021-05-03 18:47 UTC, bdarcus commented
> I get more and more convinced that the completing-read-style of doing things is the Emacs way ...

... even more so given that all of the innovation happening in this space the past year is being consolidate into patches to core Emacs, to enhance completing-read.

I learned a lot from those guys, BTW; and this package pretty much reflects their approach to these questions.

2021-05-03 18:49 UTC, bdarcus commented
PS - on org, if you've not seen it, you might want to look at #113, and links from there.

Will be particularly relevant for the `org-roam` ecosytem.