Fixed API names
bdarcus/bibtex-actions pull request #19
Opened 2021-03-08 06:33 UTC by Yevgnen

2021-03-08 17:50 UTC, bdarcus commented
Thanks for this @Yevgnen!

Can you please provide a description explaining what you did and why?

I see from your changes there's actually a mistake that you fixed, and maybe some differences of opinion on command names, which we can discuss.

2021-03-08 18:04 UTC, bdarcus commented on bibtex-actions.el
> +(defun bibtex-actions-edit-notes (keys)
See #12 for why I changed this, and the "show" example below.

2021-03-08 18:38 UTC, bdarcus commented on bibtex-actions.el
> +(defun bibtex-actions-add-pdf-attachment (keys)
Thanks; not sure how I missed this!

2021-03-09 01:05 UTC, Yevgnen commented
Hi, sorry I didn't notice #12 . I tried to fix this only since I found the keymap was broken when dealing with the bibtex completion.

2021-03-09 01:13 UTC, bdarcus commented on bibtex-actions.el
> +    (define-key map (kbd "a") 'bibtex-actions-add-PDF-attachment)
```suggestion
    (define-key map (kbd "a") 'bibtex-actions-add-pdf-attachment)
```

2021-03-09 01:18 UTC, bdarcus requested changes
You're correction of "PDF" to "pdf" was correct. I fixed that on the keymap; can you update the function name to match (not an easy way for me to do that with the web UI)?

2021-03-09 01:19 UTC, Yevgnen commented
@bdarcus Done!

2021-03-09 01:22 UTC, bdarcus approved these changes

2021-03-09 01:26 UTC, merged

2021-03-09 01:27 UTC, bdarcus commented
Merged; thanks much!

2021-03-09 13:02 UTC, bdarcus commented
PS - if you have time and interest, @Yevgnen, I could use help fixing #18. There's some subtle thing wrong with it ATM.